### ISSUE TITLE
Some color swatches do not display correctly

### ISSUE THREAD

**Issue by jake-low** [base16-project/base16-gallery#6]
I was poking around the tinted-theming org and trying to learn a bit about the project. While I was browsing I noticed that some of the color swatches on the [gallery page](https://tinted-theming.github.io/base16-gallery/) don't display correctly (they look white). Here's an example where several of the swatches in the "apathy" theme appear to be missing.

<img width="313" alt="image" src="https://user-images.githubusercontent.com/5893857/229010161-126bbf8c-98a1-487c-8b3d-1d28665df389.png">

The cause is a missing `#` in the inline CSS in `template.erb`. The swatches have `style` attributes such as `"background-color: 184E45;"`, but I think CSS requires hex colors to be prefixed with a hash, like `#184E45`. It looks like browsers correctly parse hex colors without a hash as long as the color starts with a letter and not a digit, which is why some of the swatches display but not others.

I think to fix this you just need to revert commit 6f8ce77. I was going to make a PR proposing this change but I ran into trouble running `build.sh` (the fix for the swatches worked but the code highlighting didn't; not sure if it's something specific to my vim or terminal config).

P.S. I leaned about this project because I was peeking into the source code for [flavours](https://github.com/Misterio77/flavours/), a Base16 builder and config management tool. I'm excited to see the ideas you're kicking around here (particularly in the Base17/BaseNEXT specifications which would allow styling e.g. `variable` differently than `diff_deleted`). Looking forward to watching this project progress!

**Comment by JamyGolden** [comment]
Thanks very much for catching this, the in-depth information about the issue and also being interested in tinted-theming and flavours :smile: I haven't set up the notifications properly for issues on this repo so I only saw this now, but I've reverted the commit and the colours are showing up nicely https://tinted-theming.github.io/base16-gallery/

If you're interested in being involved in any of the tinted-theming projects as a co-maintainer, let me know!
